name: CI

on: push

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Configure cache
        id: python-cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: |
            ${{ env.pythonLocation}}
          key: key-${{ runner.os }}-pip-v4-${{ hashFiles('**/requirements*.txt') }}
      - name: Install deps using Pip
        run: pip install -r requirements-dev.txt
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run linting checks
        run: |
          isort mcih --check
          black mcih --check
          flake8 mcih