files: \.py
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1  # should match requirements.txt
    hooks:
      # args are in pyproject.toml so they can be reused by IDE, command line
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0  # should match requirements_local.txt
    hooks:
      # args are in pyproject.toml so they can be reused by IDE, command line
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # should match requirements.txt
    hooks:
      # args are in .flake8 file so they can be reused by IDE, command line
      - id: flake8
