name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'src/IIIFingest/**'
      - 'tests/**'
      - .github/workflows/ci.yml
  pull_request:
  workflow_dispatch:

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements-dev.txt
            **/requirements.txt
            **/setup.cfg
      - name: Install deps using Pip
        run: pip install -r requirements-dev.txt
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run isort
        run: |
          isort src --check
      - name: Run black
        run: |
          black src --check --diff
      - name: Run flake8
        run: |
          flake8 src
      - name: Run unit tests
        run: |
          pytest tests/unit
