name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'src/IIIFingest/**'
      - 'tests/**'
      - .github/workflows/ci.yml

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      - name: Install deps using Pip
        run: pip install -r requirements-dev.txt
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run linting checks
        run: |
          isort src --check --diff
          black src --check
          flake8 src
      - name: Run unit tests
        run: |
          pytest tests/unit
