name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'src/IIIFingest/**'
      - .github/workflows/ci.yml

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Configure cache
        id: python-cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: |
            ${{ env.pythonLocation}}
          key: key-${{ runner.os }}-pip-v4-${{ hashFiles('**/requirements*.txt') }}
      - name: Install deps using Pip
        run: pip install -r requirements-dev.txt
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run linting checks
        run: |
          isort src --check
          black src --check
          flake8 src
      - name: Run unit tests
        run: |
          pytest tests/unit
