name: unit tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: '**/setup.cfg'
      - name: Install deps using Pip
        run: pip install -e ".[dev]"
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run isort
        run: |
          isort src --check
      - name: Run black
        run: |
          black src --check --diff
      - name: Run flake8
        run: |
          flake8 src